[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MendelCalculator"
authors = [{name = "MeteorShower", email = "not supported"}]
dynamic = ["version", "description"]
